### ISSUE TITLE
DONTBUILD keyword is ignored on `github-push` events

### ISSUE THREAD

**Issue by JohanLorenzo** [taskcluster/taskgraph#189]
The `DONTBUILD` keyword is a feature we implemented in taskgraph. If a commit message contains `DONTBUILD` then taskgraph doesn't schedule any taskcluster tasks ([e.g.](https://treeherder.mozilla.org/jobs?repo=mozilla-beta&revision=165cce29e43891b30dbefdcd242815d96d470691)). It works pretty well on mercurial but last week I found it doesn't work at all on Github. See this [push of firefox-android](https://treeherder.mozilla.org/jobs?repo=firefox-android&revision=b2605e96d90af6cb5894b5877bbf10fb19e7faf0). 

## Steps to reproduce

1. Follow the alternative installation steps https://github.com/taskcluster/taskgraph#installation
3. `touch FOO && git add FOO && git commit -m 'Add foo DONTBUILD` 
4. `export TASKCLUSTER_ROOT_URL='https://firefox-ci-tc.services.mozilla.com' && export TASK_ID='dummyTask'`
5. ```sh
    taskgraph decision
      --pushlog-id='0' \
      --pushdate='0' \
      --project='taskgraph' \
      --owner='some@email.tld' \
      --level='1' \
      --base-repository='https://github.com/taskcluster/taskgraph' \
      --base-ref='main' \
      --base-rev='HEAD~1' \
      --head-repository='https://github.com/taskcluster/taskgraph' \
      --head-ref='main' \
      --head-rev='HEAD' \
      --repository-type="git" \
      --tasks-for='github-push' \
      --message="Add foo DONTBUILD" \
    ```

## Expected results

The script runs successfully and and more importantly `filter_target_tasks` should prune all tasks: 

```
2023-02-20 15:13:21,469 - INFO - Filter filter_target_tasks pruned 9 tasks (0 remain)
```

## Actual results

The script fails because it schedules tasks, but more `filter_target_tasks` doesn't filter out every task.

```
2023-02-20 15:09:24,135 - INFO - Filter filter_target_tasks pruned 6 tasks (3 remain)
```

## Side notes

I recommend searching the string `DONTBUILD`. It will highlight where the fix should happen. The fix is likely a one-liner but we can use this opportunity to add more unit tests. 

After the fix, the script will still fail for another reason. Let's handle that other reason in https://github.com/taskcluster/taskgraph/issues/190.

**Comment by miladHakimi** [comment]
Hi @JohanLorenzo,
As you recommended, I searched for `DONTBUILD` string. [`decision.py` line 230](https://github.com/taskcluster/taskgraph/blob/936142a8c73510d0a0b530ac4a9a16d54cced6c9/src/taskgraph/decision.py#L230) checks if there is a "DONTBUILD" string in the commit message "And" the `task_for` option is `hg-push`. So, it makes sense that it doesn't work on `github-push` command. I can change the code to include "github-push". I can also keep a list of possible push commands which can contain push commands from other version control systems and check with all of them.
