### ISSUE TITLE
Don't hardcode Mac Python version in `run_task.py` transforms

### ISSUE THREAD

**Issue by ahal** [taskcluster/taskgraph#225]
https://github.com/taskcluster/taskgraph/blob/526f4d82906eef73ee69505c406c03f5f35de973/src/taskgraph/transforms/job/run_task.py#L209

**Comment by ahal** [comment]
This was likely ported from Gecko and never got generalized. I believe there was recently a refactor of this file around which Python to use in Gecko as well, so maybe we can copy some of the changes there.

And if not, a simple mechanism to set this per task should suffice.

**Comment by ahal** [comment]
Nvm, looks like in Gecko this is just set to `/usr/local/bin/python3` instead, which is at least a little better as it doesn't hardcode the version into it!

@MasterWayZ is `/usr/local/bin/python3` the right path to be using? Like can we count on that for all (or at least most) Mac workers?

**Comment by ahal** [comment]
I think I'll try to implement some mechanism to set this dynamically. Unsure if it should be in the `run` section of the task definition, or somewhere like `config.yml`. But this is definitely a good example of something Mozilla specific we should try and get rid of.

**Comment by ahal** [comment]
Wild idea... Re-write `run-task` in Rust (where binary is built on installation) so we don't have these worker dependent problems. Definitely not a valid solution to the immediate problem, but possibly a good idea as a follow-up.

**Comment by ddurst** [comment]
@ahal We're into a cycle already, and it'd be great to use this and work out any other issues now instead of waiting until the next cycle. Do you think this is something that could be done in this cycle (not the Rust version, of course)?

**Comment by ahal** [comment]
Version bump PR is here:
https://github.com/taskcluster/taskgraph/pull/229

**Comment by ahal** [comment]
@bendk @ddurst I just merged https://github.com/mozilla/application-services/pull/5488 into app-services. Please merge that around to any branches where the fix is required, and feel free to reach out if you need some pointers on how to workaround the Python issue.

https://github.com/mozilla/application-services/pull/5488#issuecomment-1513675693 has some details.

**Comment by bendk** [comment]
@ahal I merged main and everything is working great.  I'm using `run-task-command: ["/usr/local/bin/python3", "run-task"]` and it's working great.  Thanks for getting this fixed!

**Comment by ahal** [comment]
Awesome! And thanks for confirming that `/usr/local/bin/python3` exists on your workers :)
