### ISSUE TITLE
`.DS_Store` files should be ignored by git

### ISSUE THREAD

**Issue by JohanLorenzo** [taskcluster/taskgraph#241]
Found while reviewing https://github.com/taskcluster/taskgraph/pull/240. When writing code on macOS, `Finder` generates `.DS_Store` to cache some metadata about files in the current folder. This is a binary file that is not meant to be shared. We can easily ignore thanks to this file: 

https://github.com/taskcluster/taskgraph/blob/a0dd5d37b31b4912969b87bd57c14462cb0a1868/.gitignore#L1-L3

It should just be a matter of adding `.DS_Store` to this file.

**Comment by 0ussamaBernou** [comment]
done !

**Comment by JohanLorenzo** [comment]
Thank you @0ussamaBernou! Would you like to open a pull request to get your changes merged?

**Comment by 0ussamaBernou** [comment]
> Thank you @0ussamaBernou! Would you like to open a pull request to get your changes merged? 

Already did Thanks!

**Comment by JohanLorenzo** [comment]
Oh, I'm sorry, I'm not able to find it. Could you give me a link to your PR, @0ussamaBernou?

**Comment by ilhamalrahm** [comment]
My pull request #240 also resolves this issue now.

**Comment by 0ussamaBernou** [comment]
> Oh, I'm sorry, I'm not able to find it. Could you give me a link to your PR, @0ussamaBernou?

yeah sure, sorry for the late response, here it is https://github.com/taskcluster/taskgraph/pull/244

thought I opened a pull request earlier, but never did my bad : |

**Comment by JohanLorenzo** [comment]
Thank you both! I appreciate your efforts to make `taskgraph` easier to contribute for the first time 🙂 

I just merged #244 and rebased #240 to fix the conflict. Let me know if I missed anything.
