### ISSUE TITLE
Log the command used to invoke `run-task`

### ISSUE THREAD

**Issue by ahal** [taskcluster/taskgraph#259]
The `run-task` script should log the command used to invoke it. This information is typically available in the task definition, but it would be nice to see it in the log as well.

**Comment by yaxhkabra** [comment]
Can I work on this issue if no one is assigned to it? I am excited to do my first PR.

**Comment by yaxhkabra** [comment]
If you can mentor me on where the log information is saved. We can write a function using ` logging` to log the command everytime the `run-task` is invoked.

**Comment by ahal** [comment]
Hi @yaxhkabra, thanks for your interest! In this case we should add a new call to `print_line` immediately before this line:
https://github.com/taskcluster/taskgraph/blob/main/src/taskgraph/run-task/run-task#L1084

The `args` variable should contain the command line that used to invoke it. I'll assign you for now, looking forward to seeing a PR!

**Comment by Arunav1** [comment]
Hello sir, can I work in this issue, this willl be my first open source contribution if you can guide me through it will be very helpful, thank you so much sir.

**Comment by ahal** [comment]
Sorry @Arunav1 it looks like `yaxhkabra` already fixed this in:
https://github.com/taskcluster/taskgraph/pull/283

But we forgot to link the pull request back to this issue and close it.
