### ISSUE TITLE
`run-task` intermittently fails to clone repo on Windows with modern Git

### ISSUE THREAD

**Issue by ahal** [taskcluster/taskgraph#345]
Basti from the VPN team noticed that their new `b-win2022` worker pool has intemittent Git permission failures while cloning the repo:
```
[taskcluster 2023-09-18T18:20:35.232Z] Executing command 0: C:/mozilla-build/python3/python3.exe run-task --mozillavpn-checkout=./build/src/ --task-cwd build/src/windows/installer -- cmd.exe /c build_prod.cmd
D:\task_169506064099579>C:/mozilla-build/python3/python3.exe run-task --mozillavpn-checkout=./build/src/ --task-cwd build/src/windows/installer -- cmd.exe /c build_prod.cmd 
[setup 2023-09-18T18:20:35.398Z] run-task started in D:\task_169506064099579
[setup 2023-09-18T18:20:35.398Z] Invoked by command: --mozillavpn-checkout=./build/src/ --task-cwd build/src/windows/installer -- cmd.exe /c build_prod.cmd
[setup 2023-09-18T18:20:35.398Z] Python version: 3.9.10
[vcs 2023-09-18T18:20:35.401Z] WARNING: vcs checkout path (D:\task_169506064099579\build\src) not in cache or volume; performance will likely suffer
[vcs 2023-09-18T18:20:35.401Z] executing ['git', 'fetch', '--tags', '--force', 'https://github.com/mozilla-mobile/mozilla-vpn-client', 'refs/heads/main']
[vcs 2023-09-18T18:20:35.414Z] fatal: detected dubious ownership in repository at 'D:/task_169506064099579/build/src'
[vcs 2023-09-18T18:20:35.414Z] 'D:/task_169506064099579/build/src' is owned by:
[vcs 2023-09-18T18:20:35.414Z] 	'S-1-5-21-867665065-978626105-2054798079-1000'
[vcs 2023-09-18T18:20:35.414Z] but the current user is:
[vcs 2023-09-18T18:20:35.414Z] 	'S-1-5-21-867665065-978626105-2054798079-1001'
[vcs 2023-09-18T18:20:35.414Z] To add an exception for this directory, call:
[vcs 2023-09-18T18:20:35.414Z] 
[vcs 2023-09-18T18:20:35.414Z] 	git config --global --add safe.directory D:/task_169506064099579/build/src
```
(from [this log](https://firefox-ci-tc.services.mozilla.com/tasks/cVeBuKGhQkGDqzsoz_utkA/runs/0/logs/public/logs/live.log))

It looks like this is a feature in relatively modern Git for Windows that works around a CVE. I think `run-task` will need to set that `safe.directory` config, though tbh I'm a bit confused why this is happening intermittently in this specific case.

It looks like the checkout cache is disabled in the above log, so it shouldn't be shared across task users. `run-task` does have a bunch of confusing behaviour around dropping down from root. It looks like it creates the checkout dir as root, then drops down.. so I initially thought that was the problem.. But then why does this sometimes pass? `run-task` also calls `chown` after creating the checkout dir as root.. so I'd expect the dir to be owned by the appropriate user...

**Comment by ahal** [comment]
Then again all the dropping down from root stuff is posix-only, so probably not applicable here. I'm not really sure how user permissions and Windows works tbh.. Probably best to just set `safe.directory`

**Comment by ahal** [comment]
> The build directory in the referenced task is mounted from a cache, and already contains a clone, presumably created by a previous task, with a different user id?

Oh good eye.. Why do we get the "not in cache or volume" warning then? :/

**Comment by jcristau** [comment]
That warning seems to be based off the TASKCLUSTER_CACHES / TASKCLUSTER_VOLUMES env variables, which taskgraph only seems to use in the docker-worker case, not for g-w.

**Comment by ahal** [comment]
Doh.. thanks for digging into that. I'll file a separate issue for that.
