### ISSUE TITLE
Could `taskgraph init` make it possible to configure the project name ?

### ISSUE THREAD

**Issue by julienw** [taskcluster/taskgraph#347]
Currently `taskgraph init` uses the current directory name, but it's not always the best name to use for a project. Instead it should ask about it (with the directory name as a default) and/or make it possible to pass it on the command line.

Thanks!

**Comment by ahal** [comment]
I think what we really want here is the name of the remote repo, as it'll need to match what's configured in `ci-configuration` and that's typically what we use when setting that up. Should be possible to extract this automatically, and fallback to the directory name if there aren't any remotes. There's already logic in Taskgraph for finding a default remote to use.

It should already be possible to run `taskgraph init --prompt`, but then you need to fill out all the context values, not just the name.

**Comment by ahal** [comment]
This was fixed by #349
