### ISSUE TITLE
Enable Dependabot and Code Scanning alerts

### ISSUE THREAD

**Issue by matt-boris** [taskcluster/taskgraph#36]
To help stay on top of security issues that may become present in the project, I propose that Dependabot and Code Scanning alerts should be enabled for this repository.

https://github.com/taskcluster/taskgraph/security

**Comment by ahal** [comment]
Good call!

One issue with Dependabot is that we use `pip-compile-multi` and Dependabot doesn't support it (the PRs it creates aren't valid for it). I'd like to move away from `pip-compile-multi`, but we use this tool across all releng repos and there's an argument to be made that consistency is more important.

Maybe there's a way we can still get alerted about dependency updates, but not have the PRs automatically created... I'll do some digging.

**Comment by ahal** [comment]
These should be enabled now. I'm not 100% sure what dependabot is going to do, but I'll keep an eye on it and adjust / disable it again if necessary.
