### ISSUE TITLE
optimizations should always log verbosely in a separate log

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskgraph#523]
It is often very difficult to understand why a task was _not_ optimized away after `taskgraph` has run, in part because optimizations often depend on the state of, eg: the Taskcluster index, at the moment in time taskgraph ran. When run with verbose logging we get a lot of extra information, but this only helps if we can reproduce locally.

In order to improve debugability (but avoid cluttering up the main log) we should always verbosely log optimizations to their own logfile.

**Comment by ahal** [comment]
See also:
https://github.com/taskcluster/taskgraph/pull/508
