### ISSUE TITLE
Unpinned dependencies

### ISSUE THREAD

**Issue by larseggert** [taskcluster/taskgraph#531]
Pulling in Taskcluster via https://github.com/mozilla/neqo/pull/1935 made neqo's [OSSF score](https://securityscorecards.dev/viewer/?uri=github.com/mozilla/neqo) drop because of unpinned dependencies in taskcluster:

Reason
dependency not pinned by hash detected -- score normalized to 7
Details
Warn: containerImage not pinned by hash: .taskcluster/docker/linux/Dockerfile:1: pin your Docker image by updating alpine:latest to alpine:latest@sha256:b89d9c93e9ed3597455c90a0b88a8bbb5cb7188438f70953fede212a0c4394e0
Warn: pipCommand not pinned by hash: .taskcluster/docker/linux/Dockerfile:14-15

**Comment by jcristau** [comment]
These look like issues in neqo not in taskgraph.  Closing.

**Comment by larseggert** [comment]
Yeah, no. The file `.taskcluster/docker/linux/Dockerfile` was created by `taskgraph init`; we made no modifications.

**Comment by jcristau** [comment]
I mean sure, but if neqo's policy is to pin those dependencies then you can make those modifications.

**Comment by larseggert** [comment]
I can of course. I was just assuming taskcluster would like to ship a hardened default.

**Comment by ahal** [comment]
Hey @larseggert ,

If you're filing this based off the openssf scorecard, we do pin our dependencies in CI. But we use a technology that openssf doesn't know about so it gives us a bad score erroneously.

As far as pinning in the package itself, that would be bad practice as that would lead to impossible to resolve conflicts for our consumers.

One minor correction too, this isn't the Taskcluster repo (that's taskcluster/taskcluster). This is Taskgraph, which is a tool to help generate task definitions which then get submitted to taskcluster.
