### ISSUE TITLE
Schedule tasks that block other tasks first

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskgraph#532]
It seems reasonable that taskgraph could by default schedule tasks that block other tasks (i.e. where there are tasks that have the task as a dependency) with a higher priority. In taskcluster CI itself, I believe we have build/test tasks that don't run unless the linter passes. However, sometimes the linter is the last task to run, and only when it has run will the other tasks that depend on it get scheduled, and only then will Worker Manager start requesting instances to run the tasks on.

If there are say 10 tasks in a graph, but one of them blocks a further 5 tasks, it seems reasonable that that one task could be scheduled first. To achieve this, we already have priority field, so it seems reasonable to just bump the priority, so that all tasks that block other tasks run first, followed by tasks that don't block other tasks. There is even an argument that the priority should be a function of how many tasks the task blocks, but that might be over-optimising for now.

**Comment by jcristau** [comment]
Today, at least in firefox CI, task priority is a function of the project not individual tasks.
I have a feeling if we wanted more granularity within a single project / task group, then we'd need more than 8 possible overall values to avoid collisions and unwanted side effects.

**Comment by petemoore** [comment]
Perhaps taskgraph can retain priority, but sequence the queue.createTask calls so that tasks that have dependents run first?

**Comment by petemoore** [comment]
@jcristau highlighted that tasks are created in parallel, in which case, we can just bump priority of tasks we want to run first manually, and not have taskgraph try to be too clever about it. 👍 
Closing this as a non-issue.

**Comment by petemoore** [comment]
I guess there would be an option to create the tasks in parallel that have dependencies first, and then create the tasks in parallel which don't have dependencies, but maybe then things are becoming a bit too magical.
