### ISSUE TITLE
fetch-content sometimes ends up fetching corrupt files

### ISSUE THREAD

**Issue by bhearsum** [taskcluster/taskgraph#538]
A recent example is in https://firefox-ci-tc.services.mozilla.com/tasks/IujzQFOHSyarfuGZTqYOHg/runs/0/logs/public/logs/live.log.

Something definitely went wrong with the download of `file.17.out.zst` here. It, and another file from the task log:
```
https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/EhFkOBKCTOi5Vt5wMLJyOA/artifacts/public/build/file.4.out.zst resolved to 136533813 bytes with sha256 93e25e98fb56696dd562c99bfb63ceac87cd27e1a9b324b6f1089989fae24c05 in 7.914s
https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/UBpNNGbKRdK19sBoRLRarA/artifacts/public/build/file.17.out.zst resolved to 133492367 bytes with sha256 c353ff408dbcde93825824c2c935bcc0d0f0d67cf4b97a8589e66a7366b17ffc in 7.970s
```

Yet when I download myself, I get a match for `4`, but different results for `17`:
```
~/tmp/2024-07-09 ❯ sha256sum *   
4999a845ad51b64a7041cf2152c4a926c3ba6275bb05cd7cb82644f2e410137d  file.17.out.zst
93e25e98fb56696dd562c99bfb63ceac87cd27e1a9b324b6f1089989fae24c05  file.4.out.zst
~/tmp/2024-07-09 ❯ ls -l
total 266780
-rw-rw-r-- 1 bhearsum bhearsum 136633331 Jun 17 11:16 file.17.out.zst
-rw-rw-r-- 1 bhearsum bhearsum 136533813 Jun 17 11:21 file.4.out.zst
```

I thought there were ways HTTP guarded against this, but perhaps the fact that [we stream downloads](https://github.com/taskcluster/taskgraph/blob/9567ad16897098983796a92be576e4ca87b3c9e3/src/taskgraph/run-task/fetch-content#L191-L200) prevents that from working?

We do have a `verify-hash` option. Theoretically, we could add retries on a hash mismatch, but that only works where chain of trust is enabled. Any fix for this would preferably be universal.

**Comment by jcristau** [comment]
We should port these changes from gecko's fetch-content:
https://bugzilla.mozilla.org/show_bug.cgi?id=1884685
https://bugzilla.mozilla.org/show_bug.cgi?id=1886737
https://bugzilla.mozilla.org/show_bug.cgi?id=1885155
