### ISSUE TITLE
check_task_dependencies should also check `soft-dependencies` and `if-dependencies`

### ISSUE THREAD

**Issue by bendk** [taskcluster/taskgraph#74]
There's code in [transforms.task](https://github.com/taskcluster/taskgraph/blob/main/src/taskgraph/transforms/task.py#L1177) to check if a task exceeds `MAX_DEPENDENCIES`.  However, it only checks the dependencies key, not `soft-dependencies` or `if-dependencies`.  This lead to the app-services nightly-alert task passing that validation check, but failing the validation check when it came to POST the data (https://firefox-ci-tc.services.mozilla.com/tasks/Ot_koH-ISoeWy4EI5zZ3Gw/runs/0/logs/public/logs/live.log)

**Comment by JohanLorenzo** [comment]
For people interested in this good first bug: the change has to be made here: 

https://github.com/taskcluster/taskgraph/blob/389ef97a27259ec314dfa5c019ffc203cf033d87/src/taskgraph/transforms/task.py#L1243-L1256

Testing the fix can be done by writing a new unit test similar to this one:

https://github.com/taskcluster/taskgraph/blob/389ef97a27259ec314dfa5c019ffc203cf033d87/test/test_transforms_task.py#L146-L167

There, we should assert that an error is raised or not depending on how many `dependencies`, `if-dependencies`, and `soft-dependencies` are defined. 

I'm happy to mentor this issue 🙂

**Comment by ilhamalrahm** [comment]
I have updated "check_task_dependencies" to check for "soft-dependencies" as well as "if-dependencies".
i have written unit test "test_check_task_dependencies" to test the fix.
