### ISSUE TITLE
Support Git repositories in `files_changed.py` and `skip-unless-changed` optimization strategy

### ISSUE THREAD

**Issue by ahal** [taskcluster/taskgraph#81]
This strategy raises a RuntimeError if used on a Git repo:
https://github.com/taskcluster/taskgraph/blob/b4081f459831cc24fafb9687d8fca77c260f8c6b/src/taskgraph/optimize.py#L455

This is because `files_changed.py` queries `hg.m.o` to retrieve the files. Though there's no reason it couldn't query e.g [Github](https://docs.github.com/en/rest/pulls/pulls#list-pull-requests-files) for this information as well. Though I'm unsure whether there's an API for pushes...

Alternatively maybe this information could be found locally by comparing the head REF to the origin branch and `git diff-tree` or something similar.

A bit of thought is needed here, but it should be do-able for most cases.

**Comment by JohanLorenzo** [comment]
Great news: we don't need to query the git server! There's a simple git command to use. I actually implemented `skip-unless-changed` in jobgraph. It was fairly straightforward! 😃 

* https://gitlab.com/jobgraph-dev/jobgraph/-/blob/c778983711a9d2aa3f0f80f878b8dc2856be9480/src/jobgraph/optimize/__init__.py#L296-L298
* https://gitlab.com/jobgraph-dev/jobgraph/-/blob/c778983711a9d2aa3f0f80f878b8dc2856be9480/src/jobgraph/util/vcs.py#L202-L205

**Comment by ahal** [comment]
Nice, yeah and the `base_ref` attribute there is also a pretty magical (in a good sense) way of finding a "parent" revision to compare against.

Actually, looks like we have something similar in Gecko:
https://searchfox.org/mozilla-central/source/python/mozversioncontrol/mozversioncontrol/__init__.py#584

Which I guess was implemented for the benefit of git-cinnabar users. So this should just be a matter of upstreaming that. We can probably stop relying on `json-automationrelevance` for the `hg` case too if we wanted...

**Comment by ahal** [comment]
Nice!

Note it *might* still be possible to do this locally, we have this function in Gecko:
https://searchfox.org/mozilla-central/source/python/mozversioncontrol/mozversioncontrol/__init__.py#601

Which ultimately runs:
`git log --name-only --oneline --pretty=format: HEAD --not --remotes`

But I wouldn't be surprised if there are edge cases that isn't handling, so agree that using Github's API feels less error prone here..

**Comment by JohanLorenzo** [comment]
My apologies. I just read my last comment again and I realize how ambiguous it was. I've been working on upstreaming the code we have in `mozversioncontrol`. It already has tests and years of testing behind it. Moreover, I prefer when the decision task run as many offline operations as possible. Sorry for the confusion I caused! 😅

**Comment by ahal** [comment]
Sounds good, though I think the Github case is trickier than the mozilla-central case. Right now, the default for `get_files_changed` on Git is to pass in `--not --remotes` to `git log`. So if someone pushes their changes to the `myrepo/my-feature` branch, then they push to the `myrepo/main` branch, files changed would be empty as the changes all exist on a remote branch. I think it's solvable by ensuring we explicitly pass an `upstream` value in.. Though I wouldn't be surprised if there are other edge cases.

We don't do branch based development in Gecko, so we haven't had to worry about this kind of thing there yet.

**Comment by JohanLorenzo** [comment]
Great point! I think we should let `get_files_changed()` accept a `base_rev` parameter. This way, the result of this function doesn't depend on what is on the remote repository. If we go down that route, then we will introduce a breaking change: `base_rev` will become a taskgraph parameter and `.taskcluster.yml` will have to provide it.

Personally, I'm fine with that change - I actually made it in jobgraph[1]. It's pretty easy to implement on the Github side since they provide that data in the webhook event[2]. On the hg.m.o side, it's a matter of enhancing the `push_info`[3] to include the base revision. 

If you're okay with it, I'll open a bug to track this since this goes beyond taskgraph alone.

[1] https://gitlab.com/jobgraph-dev/jobgraph/-/commit/285682359d1f3b70b2fab33b16e309573b66b72e
[2] https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#push
[3] https://hg.mozilla.org/ci/ci-configuration/file/a41d0f8feaf1131c3842780808e187e45fb1ffda/build-decision/src/build_decision/hg_push.py#l50

**Comment by ahal** [comment]
Sounds good, it sounds like it should be possible to implement this in a backwards compatible way. I.e, if `base_rev` is passed in do one thing and if it's not fallback to the old thing. Or make `base_rev` mandatory with Git but not with Hg.

Though if that would add an undue amount of complexity, breaking backwards compat is fine too.

**Comment by JohanLorenzo** [comment]
All right! I'll see what I can do. I know for a fact that in some cases, `base_rev` isn't always trustworthy and you have to fallback to another thing. I'll see that extends to all cases 🙂 

[1] For instance: https://gitlab.com/jobgraph-dev/jobgraph/-/commit/8644c2b9f7569da81e5f9d465438cf77a6b10236

**Comment by JohanLorenzo** [comment]
This issue now depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1784232
