### ISSUE TITLE
artifact-reference should support non-public artifacts

### ISSUE THREAD

**Issue by escapewindow** [taskcluster/taskgraph#90]
https://github.com/mozilla-extensions/xpi-template/issues/37
Essentially, we probably want to remove [this check](https://github.com/taskcluster/taskgraph/blob/ec733aa2c331390a0af079fa4a71e47c4622468f/src/taskgraph/util/parameterization.py#L82-L87).

Given that:

a) we can use artifact-reference for scriptworkers, which often do have private artifact scopes baked in (until we resolve https://github.com/mozilla-releng/scriptworker/issues/426, after which we'll need to grant the scope to the task as normal), and
b) if we grant the given task the proper private artifact scope and enable the taskcluster-proxy, non-scriptworker tasks can also download private artifacts,

I don't see a need for this artificial restriction.

**Comment by jcristau** [comment]
Fixed by #485
